### ISSUE TITLE
„invalid data“

### ISSUE THREAD

**Issue by tahnil** [Schamper/nodebb-plugin-eve#2]
Hi. Thanks for the plugin. Currently I‘m evaluating it. And I encountered an issue, that I seem not to be able to solve.

When I try to register it doesn‘t work. Instead the register form is re-loaded (empty) and in the address bar it says "/register?error=Invalid%20data".

Maybe a problem with my database, as I migrated an SMF forum to NodeBB with a lot of existing users. EVE API data should be okay though. The right EVE character is shown in the dropdown list. Access key is correct as well.

I tried different (non-existing) E-Mail addresses and usernames – no effect.

**Comment by Schamper** [comment]
So according to the code, `Invalid data` is returned when the API call fails:
https://github.com/Schamper/nodebb-plugin-eve/blob/bd8650c0ba0d66eedb7d8ff3951841ffc05cba36/library.js#L191

If you could perhaps supply me with the keyId and vCode that you're having trouble with (in private ofcourse), I can try to debug it.

You can send me a PM on either http://bitbangers.co.uk/ or https://community.nodebb.org/

**Comment by Schamper** [comment]
So I figured out what the problem was. You're not in an alliance, so trying to get info about your alliance causes an error. It'll be fixed in the next release.
